app_architektura:
    path: /
    controller: App\Controller\AppController::indexAction
app_architektura_register:
    path: /register
    controller: App\Controller\AppController::registerAction
app_architektura_login:
    path: /login
    controller: App\Controller\SecurityController::login
app_architektura_logout:
    path: /logout
app_architektura_admin_dashboard:
    path: /admin
    controller: App\Controller\AdminController::dashboardAction
app_architektura_admin_profile:
    path: /admin/profile
    controller: App\Controller\AdminController::profile
app_architektura_admin_survey_list:
    path: /admin/survey/list
    controller: App\Controller\SurveyController::surveyList
app_architektura_admin_survey_add:
    path: /admin/survey/add
    controller: App\Controller\SurveyController::add
app_architektura_admin_survey_edit:
    path: /admin/survey/edit/{id}
    controller: App\Controller\SurveyController::edit
    requirements:
        id: '\d+'
app_architektura_admin_survey_questions:
    path: /admin/survey/edit/{id}/questions
    controller: App\Controller\SurveyController::questions
    requirements:
        id: '\d+'
app_architektura_admin_ajax_question_add:
    path: /admin/question/add
    controller: App\Controller\SurveyController::ajaxAddQuestion
app_architektura_admin_ajax_question_new_form:
    path: /admin/question/form/new
    controller: App\Controller\SurveyController::ajaxGetQuestionNewForm
        
        
app_architektura_survey:
    path: /survey/{id}/{slug}
    controller: App\Controller\SurveyController::edit
    requirements:
        id: '\d+'