app_architektura:
    path: /
    controller: App\Controller\AppController::indexAction
app_architektura_register:
    path: /register
    controller: App\Controller\AppController::registerAction
app_architektura_login:
    path: /login
    controller: App\Controller\SecurityController::login
app_architektura_logout:
    path: /logout
app_architektura_admin_dashboard:
    path: /admin
    controller: App\Controller\AdminController::dashboardAction
app_architektura_admin_profile:
    path: /admin/profile
    controller: App\Controller\AdminController::profile
app_architektura_admin_survey_add:
    path: /admin/survey/add
    controller: App\Controller\SurveyController::add